### ISSUE TITLE
How to use this library to build btc multi-signature transactions?

### ISSUE THREAD

**Issue by vendersen** [cmdruid/musig2#2]
Please.

**Comment by cmdruid** [comment]
Just use the group pubkey as the internal key for the taproot tx, and have everyone sign the same sighash.

**Comment by UIZorrot** [comment]
It's actually a ver good question, and I'd like to ask about it too. That's:

How to let everyone sign the same sighash?

Like using bitcoinjs-lib, it is seemed hard to dump the sighash from a `psbt` struct. But using the `Signinput` function is useless in this situation, it takes me about a week and I can't figure it out.

I think the very nature way to do this was:

[pub1, pub2 .. pubn] -> pub_agg -> p2tr(internalpubkey : pub_agg) -> build psbt -> musig( pub_agg, [priv1 .. privn], hash ) -> data.input.push(musig) -> broadcast

I find it difficult in `musig( pub_agg, [priv1 .. privn], hash )`, about:

1. what is this `hash` exactly? Is it the sha256(WitnessUTXO.script)?
2. how to get this hash using bitcoinjs-lib?

I think it's not NEED TO BE ANSWERED because it's quietly a general discussion and not related much with this repo.
